name: Open-CE-Common PR Job

on:
  pull_request:
    branches:
      - 'main'        # matches the main branch
      - 'open-ce-common-r*'  # matches every release branch

jobs:
  release_dry_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: conda-incubator/setup-miniconda@v2.0.0
        with:
          auto-update-conda: true
          python-version: "3.10"
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda install -y python=3.10 conda=23.7.3 conda-build=3.22
